services:
  proxy:
    image: ubuntu/squid
    ports:
      - 3128:3128
    # labels:
      # optional updates using watchtower
      # com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
      - ./passwords:/etc/squid/passwords
