services:
  proxy:
    image: ubuntu/squid
    ports:
      - 8118:3128
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
      - ./passwords:/etc/squid/passwords
